"""Documentation operations for DAF."""

from pathlib import Path


def _find_at_daf_dir():
    """Find the @daf directory reliably."""
    current_dir = Path.cwd()

    # Check current directory first
    potential_at_daf = current_dir / "@daf"
    if potential_at_daf.exists():
        return potential_at_daf

    # Check parent directory
    potential_at_daf = current_dir.parent / "@daf"
    if potential_at_daf.exists():
        return potential_at_daf

    return None


def regenerate_docs():
    """Regenerate @daf documentation from Metta repository using real source code analysis."""
    try:
        print("🔄 Regenerating @daf documentation from Metta source code...")

        # Import the real documentation generation tools
        import sys
        from pathlib import Path

        # Add the tools directory to path
        tools_dir = Path(__file__).parent.parent / "tools"
        if str(tools_dir) not in sys.path:
            sys.path.insert(0, str(tools_dir))

        # Import and run the real documentation generator
        try:
            from comprehensive_generator import generate_comprehensive_daf_docs

            # First check if inventory exists, if not, create it
            inventory_path = Path("/tmp/metta_inventory.json")
            if not inventory_path.exists():
                print("📡 Metta inventory not found. Scanning repository first...")
                from sync_with_metta import scan_metta_repository

                metta_inventory = scan_metta_repository()
                with open(inventory_path, "w") as f:
                    import json

                    json.dump(metta_inventory, f, indent=2, default=str)
                print(f"✅ Created inventory for {len(metta_inventory)} modules")

            # Generate the comprehensive documentation
            success = generate_comprehensive_daf_docs()

            if success:
                print("✅ Documentation regeneration completed successfully!")
                print("   📁 Created @daf directory with real documentation")
                print("   📚 Generated documentation from actual Metta source code")
                print("   📊 Analyzed classes, functions, and methods with signatures")
            else:
                print("⚠️  Documentation generation completed with warnings")
                return True

            return True

        except ImportError as e:
            print(f"❌ Could not import documentation tools: {e}")
            print("   📝 Falling back to placeholder generation...")

            # Fallback to placeholder creation
            return _create_placeholder_docs()

    except Exception as e:
        print(f"❌ Error during documentation regeneration: {e}")
        print("   📝 Falling back to placeholder generation...")
        try:
            return _create_placeholder_docs()
        except:
            return False


def _create_placeholder_docs():
    """Create basic placeholder documentation structure."""
    print("📝 Creating placeholder documentation structure...")

    # Find @daf directory
    at_daf_dir = _find_at_daf_dir()
    if at_daf_dir is None:
        at_daf_dir = Path("@daf")
        at_daf_dir.mkdir(exist_ok=True)

    # Create structure directory
    structure_dir = at_daf_dir / "structure"
    structure_dir.mkdir(exist_ok=True)

    # Create a basic README for the @daf directory
    readme_content = """# @daf - Autogenerated Metta Documentation

This directory contains automatically generated documentation from the Metta repository.

## Directory Structure

- `methods/` - Individual method documentation files
- `structure/` - Repository structure metadata and analysis

## Usage

Use this documentation to understand available Metta methods and their signatures.

## Regenerated

$(date)

---
**Auto-generated documentation for Metta methods**
"""

    readme_file = at_daf_dir / "README.md"
    readme_file.write_text(readme_content)

    # Create structure metadata files
    structure_files = {
        "METTA_REPOSITORY_STRUCTURE.md": "# Metta Repository Structure\n\nAuto-generated structure documentation.\n",
        "method_distribution.json": '{"modules": {}, "total_methods": 0}',
        "module_dependencies.json": '{"dependencies": {}}',
        "integration_patterns.md": "# Integration Patterns\n\nAuto-generated integration documentation.\n",
    }

    for filename, content in structure_files.items():
        (structure_dir / filename).write_text(content)

    print("✅ Placeholder documentation regeneration completed!")
    print("   📁 Created @daf directory structure")
    print("   📚 Generated placeholder documentation")
    print("   📊 Created structure metadata files")
    return True


def list_metta_options():
    """List all available real Metta options and methods."""
    try:
        # Find @daf directory
        at_daf_dir = _find_at_daf_dir()
        if at_daf_dir is None:
            print("❌ @daf directory not found. Run 'python daf_main.py docs regenerate' first.")
            return False

        print("\n" + "=" * 80)
        print("🎯 REAL METTA METHODS AND OPTIONS")
        print("=" * 80)

        # List method documentation files (directly in @daf directory)
        method_files = sorted(at_daf_dir.glob("*.md"))
        # Filter out README and structure files, keep only method docs
        method_files = [
            f
            for f in method_files
            if f.name not in ["README.md"]
            and not f.name.startswith("METTA_")
            and not f.name.endswith("_patterns.md")
            and not f.name.endswith("_dependencies.json")
            and not f.name.endswith("_distribution.json")
        ]

        if method_files:
            print(f"\n📚 Method Documentation ({len(method_files)} files):")
            for i, method_file in enumerate(method_files[:10], 1):  # Show first 10
                print(f"   {i:2d}. {method_file.name}")
            if len(method_files) > 10:
                print(f"   ... and {len(method_files) - 10} more files")

        # List structure documentation
        structure_dir = at_daf_dir / "structure"
        if structure_dir.exists():
            print("\n📊 Structure Documentation:")
            structure_files = list(structure_dir.glob("*.md")) + list(structure_dir.glob("*.json"))
            for structure_file in structure_files:
                print(f"   • {structure_file.name}")

        # Show real usage examples
        print("\n🚀 Real Metta Usage Examples:")
        print("   • python daf_main.py examples  # Run all examples")
        print("   • daf/examples/                # Browse example files")
        print("   • daf/tests/                   # Test suite with real components")

        # Show integration patterns
        print("\n🔧 Integration Options:")
        print("   • Adaptive Learning: metta.adaptive.adaptive_controller")
        print("   • RL Training: metta.rl.trainer")
        print("   • Curriculum Learning: metta.cogworks.curriculum")
        print("   • Experiment Tracking: metta.adaptive.stores.wandb")
        print("   • Configuration: metta.setup.saved_settings")

        # Show available commands
        print("\n⚡ Available DAF Commands:")
        print("   • python daf_main.py setup        # Complete setup")
        print("   • python daf_main.py validate     # Validation")
        print("   • python daf_main.py examples     # Run examples")
        print("   • python daf_main.py test         # Run tests")
        print("   • python daf_main.py docs regenerate  # Regenerate docs")
        print("   • python daf_main.py status       # Show status")

        print("\n" + "=" * 80)
        return True

    except Exception as e:
        print(f"❌ Error listing Metta options: {e}")
        return False


def run_docs():
    """Documentation operations dispatcher."""
    import argparse

    parser = argparse.ArgumentParser(description="DAF Documentation Operations")
    subparsers = parser.add_subparsers(dest="docs_command", help="Documentation operation")

    # Regenerate command
    subparsers.add_parser("regenerate", help="Regenerate @daf documentation")

    # List command
    subparsers.add_parser("list", help="List all real Metta options")

    args = parser.parse_args()

    if args.docs_command == "regenerate":
        return regenerate_docs()
    elif args.docs_command == "list":
        return list_metta_options()
    else:
        print("❌ Unknown docs command. Use 'regenerate' or 'list'")
        return False
