# Default environment configuration for testing
_target_: mettagrid.Grid
name: default_test_env

# Grid parameters
width: 10
height: 10

# Observation parameters
vision_radius: 5
num_channels: 3  

# Agent parameters
num_agents: 2

# Action parameters
action_space:
  - move
  - rotate
  - noop

# Other parameters
frame_rate: 30
max_steps: 100 